"""Definitions of field labels and indices."""

from enum import StrEnum


class Fields(StrEnum):
    DOB_YY = "dob_yy"
    """Year of birth"""
    DOB_MM = "dob_mm"
    """Month of birth"""
    BFACIL = "bfacil"
    """Birth place"""
    F_BFACIL = "f_bfacil"
    """Reporting flag for birth place"""
    MAGE_IMPFLG = "mage_impflg"
    """Mother's Age Imputed: Due to missing data, age imputed"""
    MAGE_REPFLG = "mage_repflg"
    MAGER = "mager"
    """Mother's Single Years of Age"""
    MAGER14 = "mager14"
    MAGER9 = "mager9"
    MBSTATE_REC = "mbstate_rec"
    RESTATUS = "restatus"
    MRACE31 = "mrace31"
    MRACE6 = "mrace6"
    MRACE15 = "mrace15"
    MRACEIMP = "mraceimp"
    MHISPX = "mhispx"
    MHISP_R = "mhisp_r"
    F_MHISP = "f_mhisp"
    MRACEHISP = "mracehisp"
    MAR_P = "mar_p"
    DMAR = "dmar"
    MAR_IMP = "mar_imp"
    F_MAR_P = "f_mar_p"
    MEDUC = "meduc"
    F_MEDUC = "f_meduc"
    FAGERPT_FLG = "fagerpt_flg"
    FAGECOMB = "fagecomb"
    FAGEREC11 = "fagerec11"
    FRACE31 = "frace31"
    FRACE6 = "frace6"
    FRACE15 = "frace15"
    FHISPX = "fhispx"
    FHISP_R = "fhisp_r"
    F_FHISP = "f_fhisp"
    FRACEHISP = "fracehisp"
    FEDUC = "feduc"
    PRIORLIVE = "priorlive"
    PRIORDEAD = "priordead"
    PRIORTERM = "priorterm"
    LBO_REC = "lbo_rec"
    TBO_REC = "tbo_rec"
    PRECARE = "precare"
    PAY = "pay"
    PAY_REC = "pay_rec"
    F_PAY = "f_pay"
    F_PAY_REC = "f_pay_rec"
    SEX = "sex"
    CA_ANEN = "ca_anen"
    CA_MNSB = "ca_mnsb"
    CA_CCHD = "ca_cchd"
    CA_CDH = "ca_cdh"
    OMPH = "ca_omph"
    CA_GAST = "ca_gast"
    F_CA_ANEN = "f_ca_anen"
    F_CA_MENIN = "f_ca_menin"
    F_CA_HEART = "f_ca_heart"
    F_CA_HERNIA = "f_ca_hernia"
    F_CA_OMPHA = "f_ca_ompha"
    F_CA_GASTRO = "f_ca_gastro"
    CA_LIMB = "ca_limb"
    CA_CLEFT = "ca_cleft"
    CA_CLPAL = "ca_clpal"
    DOWNS = "downs"  # from 1989 to 2002
    UCA_DOWNS = "uca_downs"  # 2003
    CA_DOWN = "ca_down"  # from 2004 onward
    CA_DOWNS = "ca_downs"  # with s 2012 - 2017
    CA_DOWN_C = "ca_down_c"  # combined
    CA_DISOR = "ca_disor"
    CA_HYPO = "ca_hypo"
    F_CA_LIMB = "f_ca_limb"
    F_CA_CLEFT = "f_ca_cleftlp"
    F_CA_CLPAL = "f_ca_cleft"
    F_CA_DOWN = "f_ca_down"
    F_CA_DOWNS = "f_ca_downs"
    F_CA_DISOR = "f_ca_chrom"
    F_CA_HYPO = "f_ca_hypos"
    NO_CONGEN = "no_congen"
    F_MPCB = "f_mpcb"
    PRECARE5 = "precare5"
    PREVIS = "previs"
    PREVIS_REC = "previs_rec"
    F_TPCV = "f_tpcv"
    WIC = "wic"
    F_WIC = "f_wic"

    DS = "ds"  # phase out for DS_CORP

    DS_C = "ds_c"
    DS_P = "ds_p"
    DS_N = "ds_n"
    DS_U = "ds_u"
    DS_CORP = "ds_corp"

    P_DS_LB_NT = "p_ds_lb_nt"
    """Probability of Down syndrome live birth absent terminations. Estimated from maternal age using Morris formula."""

    P_DS_LB_WT = "p_ds_lb_wt"
    """Probability of Down syndrome live birth with terminations. Estimated from surveillance-based prevalence"""